### ISSUE TITLE
Doesn't work in python3.8

### ISSUE THREAD

**Issue by paulquevedojdrf** [AharonSambol/PrettyPrintTree#14]
Doesn't run on python3.8
The type hint `list[str]` isn't valid in py3.8. Change to `list`

https://github.com/AharonSambol/PrettyPrintTree/blob/c4d6e00b3b505f9b775e6207d8096f3038de274b/PrettyPrint/Utils/NodeFormatter.py#L15

```
Traceback (most recent call last):
  File "productcode.py", line 371, in <module>
    print_tree()
  File "productcode.py", line 295, in print_tree
    from PrettyPrint import PrettyPrintTree
  File "/home/pquevedo/dev/fw-thor/scripts/deploy/env3.8/lib/python3.8/site-packages/PrettyPrint/__init__.py", line 1, in <module>
    from .PrintTree import PrettyPrintTree
  File "/home/pquevedo/dev/fw-thor/scripts/deploy/env3.8/lib/python3.8/site-packages/PrettyPrint/PrintTree/__init__.py", line 1, in <module>
    from .TreePrinter import PrettyPrintTree
  File "/home/pquevedo/dev/fw-thor/scripts/deploy/env3.8/lib/python3.8/site-packages/PrettyPrint/PrintTree/TreePrinter.py", line 4, in <module>
    from PrettyPrint.PrintTree.TreeFormatter import TreeFormatter
  File "/home/pquevedo/dev/fw-thor/scripts/deploy/env3.8/lib/python3.8/site-packages/PrettyPrint/PrintTree/TreeFormatter.py", line 3, in <module>
    from PrettyPrint.PrintTree.HorizontalTree import join_vertically, add_parent as add_parent_left
  File "/home/pquevedo/dev/fw-thor/scripts/deploy/env3.8/lib/python3.8/site-packages/PrettyPrint/PrintTree/HorizontalTree.py", line 1, in <module>
    from PrettyPrint.Utils.NodeFormatter import NodeFormatter
  File "/home/pquevedo/dev/fw-thor/scripts/deploy/env3.8/lib/python3.8/site-packages/PrettyPrint/Utils/NodeFormatter.py", line 5, in <module>
    class NodeFormatter:
  File "/home/pquevedo/dev/fw-thor/scripts/deploy/env3.8/lib/python3.8/site-packages/PrettyPrint/Utils/NodeFormatter.py", line 15, in NodeFormatter
    lines: list[str], *, height: int, width: int,
TypeError: 'type' object is not subscriptable
```

**Comment by AharonSambol** [comment]
Oops, thanks for pointing that out, it should be fixed in the new version (2.0.1)
